version: '3'

services:

  backend:
    container_name: 'backend'
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    command:
      bash -c "
              python wait_db.py &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py collectstatic --no-input &&
              gunicorn project.wsgi -b 0.0.0.0:8000 --workers=4"
    volumes:
      - ./backend:/backend
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE:project.settings.docker_prod
    depends_on:
      - db
      - frontend
    links:
      - db:database
      - frontend:frontend
    restart: always

  frontend:
    container_name: 'frontend'
    build: ./frontend/
    command: npm run build
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - ./backend:/backend

volumes:
  database:
