version: '3.6'

services:

  db:
    container_name: 'postgres'
    image: postgres
    expose:
      - 5432
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: 'redis'
    image: redis:latest
    expose:
      - 6379

  backend:
    container_name: 'backend'
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command:
      bash -c "
              python wait_db.py &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py collectstatic --no-input &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE:project.settings.docker_dev
    depends_on:
      - db
      - frontend
      - redis
    links:
      - db:database
      - frontend:frontend
      - redis:redis
    restart: always

  frontend:
    container_name: 'frontend'
    build: ./frontend/
    command: npm run dev
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - ./backend:/backend

  webserver:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./backend/static/:/static
      - ./config/nginx:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    links:
      - backend:backend
    restart: always

volumes:
  database: