version: '3.6'

services:
  db:
    container_name: 'postgres'
    image: postgres
    expose:
      - 5432
    volumes:
      - ./database:/var/lib/postgresql/data
  backend:
    container_name: 'backend'
    build: ./backend/
    command:
      bash -c "
              python wait_db.py &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py collectstatic --no-input &&
              python manage.py runserver 0.0.0.0:8000"
#              gunicorn --reload backend.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE:project.settings.docker
    depends_on:
      - db
      - frontend
    links:
      - db:database
      - frontend:frontend
    restart: always
  frontend:
    container_name: 'frontend'
    build: ./frontend/
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - ./backend:/backend
  webserver:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./backend/static/:/static
      - ./config/nginx:/etc/nginx/conf.d/default.conf
#      - ./logs:/var/log/nginx
    depends_on:
      - backend
    links:
      - backend:backend
    restart: always

volumes:
  database: