FROM python:3.7

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE project.settings.testing

RUN pip install --upgrade pip

WORKDIR /backend/

COPY . /backend/

RUN pip install -r requirements.txt
